/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crim_locked;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author -Kasun Dissanayake-
 */
public class SearchWitness extends javax.swing.JFrame {

    /**
     * Creates new form SearchWitness
     */
    
    public SearchWitness() {
        
        initComponents();        
    }
    
    
        

    
        
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        areaCombo = new javax.swing.JComboBox<>();
        genderCombo = new javax.swing.JComboBox<>();
        heightCombo = new javax.swing.JComboBox<>();
        skinColorCombo = new javax.swing.JComboBox<>();
        hairCombo = new javax.swing.JComboBox<>();
        eyeCombo = new javax.swing.JComboBox<>();
        beardCombo = new javax.swing.JComboBox<>();
        tattooButton = new javax.swing.JButton();
        scarButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        beardButton = new javax.swing.JButton();
        eyeButton = new javax.swing.JButton();
        hairButton = new javax.swing.JButton();
        tattooLabel = new javax.swing.JTextField();
        scarLabel = new javax.swing.JTextField();
        hairLabel = new javax.swing.JTextField();
        eyeLabel = new javax.swing.JTextField();
        beardLabel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Search Criminal Form");

        jLabel2.setText("Area");

        jLabel3.setText("Gender");

        jLabel4.setText("Height");

        jLabel5.setText("Skin Colour");

        jLabel6.setText("Hair");

        jLabel7.setText("Eye");

        jLabel8.setText("Beard");

        jLabel9.setText("Tattoos");

        jLabel10.setText("Scars");

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));

        heightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tall", "Short", "Medium", "Unknown", " " }));

        skinColorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White ", "Black", "Fair", "Unknown", " ", " " }));

        hairCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "White", "Blond", "Bold", "Unknown", " " }));
        hairCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairComboActionPerformed(evt);
            }
        });

        eyeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "Blue", "Brown", "Unknown" }));
        eyeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyeComboActionPerformed(evt);
            }
        });

        beardCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White ", "Black", "Brown", "Without Beard", "Unkown", " " }));

        tattooButton.setText("Choose");
        tattooButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tattooButtonActionPerformed(evt);
            }
        });

        scarButton.setText("Choose");
        scarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scarButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        beardButton.setText("Choose");
        beardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beardButtonActionPerformed(evt);
            }
        });

        eyeButton.setText("Choose");
        eyeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyeButtonActionPerformed(evt);
            }
        });

        hairButton.setText("Choose");
        hairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairButtonActionPerformed(evt);
            }
        });

        hairLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skinColorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton3)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(beardCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eyeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hairCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tattooButton)
                                .addComponent(scarButton))
                            .addGap(57, 57, 57)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tattooLabel)
                                .addComponent(scarLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hairButton)
                                        .addComponent(eyeButton)
                                        .addComponent(beardButton))
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(beardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                            .addComponent(eyeLabel))
                                        .addComponent(hairLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(areaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(heightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(skinColorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hairCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hairButton)
                    .addComponent(hairLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(eyeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eyeButton)
                    .addComponent(eyeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(beardCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beardButton)
                    .addComponent(beardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tattooButton)
                    .addComponent(tattooLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(scarButton)
                    .addComponent(scarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton3)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        beardLabel.getAccessibleContext().setAccessibleName("");
        beardLabel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hairLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hairLabelActionPerformed

    private void eyeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eyeComboActionPerformed

    private void hairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairButtonActionPerformed
        int index = hairCombo.getSelectedIndex();
        if(index == 0){      
            Search sh = new Search(hairLabel);
            sh.ad = "/crim_locked/images/hair/black";
            sh.setVisible(true);
            
        }
        else if(index == 1){      
            Search sh = new Search(hairLabel);
            sh.ad = "/crim_locked/images/hair/white";
            sh.setVisible(true);  
        }
        else if(index == 2){      
            Search sh = new Search(hairLabel);
            sh.ad = "/crim_locked/images/hair/blond";
            sh.setVisible(true);  
        }
        else if(index == 3){      
            Search sh = new Search(hairLabel);
            sh.ad = "/crim_locked/images/hair/bold";
            sh.setVisible(true);  
        }
        else{
            hairLabel.setText("Unknown");
        }
    }//GEN-LAST:event_hairButtonActionPerformed

    private void hairComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hairComboActionPerformed

    private void eyeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyeButtonActionPerformed
        int index = eyeCombo.getSelectedIndex();
        if(index == 0){      
            Search sh = new Search(eyeLabel);
            sh.ad = "/crim_locked/images/eyes/black";
            sh.setVisible(true);  
        }
        else if(index == 1){      
            Search sh = new Search(eyeLabel);
            sh.ad = "/crim_locked/images/eyes/blue";
            sh.setVisible(true);  
        }
        else if(index == 2){      
            Search sh = new Search(eyeLabel);
            sh.ad = "/crim_locked/images/eyes/brown";
            sh.setVisible(true);
            
        }
       
        else{
            eyeLabel.setText("Unknown");
        }
    }//GEN-LAST:event_eyeButtonActionPerformed

    private void beardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beardButtonActionPerformed
        int index = beardCombo.getSelectedIndex();
        if(index == 0){      
            Search sh = new Search(beardLabel);
            sh.ad = "/crim_locked/images/beard/white";
            sh.setVisible(true);  
        }
        else if(index == 1){      
            Search sh = new Search(beardLabel);
            sh.ad = "/crim_locked/images/beard/black";
            sh.setVisible(true);  
        }
        else if(index == 2){      
            Search sh = new Search(beardLabel);
            sh.ad = "/crim_locked/images/beard/brown";
            sh.setVisible(true);  
        }
        else if(index == 3){      
            Search sh = new Search(beardLabel);
            sh.ad = "/crim_locked/images/hair/without";
            sh.setVisible(true);  
        }
        else{
            beardLabel.setText("Unknown");
        }
    }//GEN-LAST:event_beardButtonActionPerformed

    private void tattooButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tattooButtonActionPerformed
         Search sh = new Search(tattooLabel);
         sh.ad = "/crim_locked/images/tattoos";
         sh.setVisible(true);
    }//GEN-LAST:event_tattooButtonActionPerformed

    private void scarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scarButtonActionPerformed
         Search sh = new Search(scarLabel);
         sh.ad = "/crim_locked/images/scars";
         sh.setVisible(true);
    }//GEN-LAST:event_scarButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchWitness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchWitness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchWitness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchWitness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchWitness().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> areaCombo;
    private javax.swing.JButton beardButton;
    private javax.swing.JComboBox<String> beardCombo;
    private javax.swing.JTextField beardLabel;
    private javax.swing.JButton eyeButton;
    private javax.swing.JComboBox<String> eyeCombo;
    private javax.swing.JTextField eyeLabel;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JButton hairButton;
    private javax.swing.JComboBox<String> hairCombo;
    private javax.swing.JTextField hairLabel;
    private javax.swing.JComboBox<String> heightCombo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton scarButton;
    private javax.swing.JTextField scarLabel;
    private javax.swing.JComboBox<String> skinColorCombo;
    private javax.swing.JButton tattooButton;
    private javax.swing.JTextField tattooLabel;
    // End of variables declaration//GEN-END:variables
}
